name: Publish Packages to npmjs

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.VERSION }}
    strategy:
      matrix:
        package:
          - name: "prompt-shared-state"
            path: "prompt-shared-state"
          - name: "prompt-ui-components"
            path: "prompt-ui-components"
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Extract version from release tag
        id: extract_version
        run: |
          # Extract version from release tag (e.g., v1.2.3 -> 1.2.3)
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          VERSION="${RELEASE_TAG#v}"
          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Publishing version: $VERSION"

      - name: Validate ${{ matrix.package.name }} version matches release tag
        run: |
          RELEASE_VERSION="${{ steps.extract_version.outputs.VERSION }}"
          
          # Check package version
          PACKAGE_VERSION=$(node -p "require('./${{ matrix.package.path }}/package.json').version")
          if [ "$PACKAGE_VERSION" != "$RELEASE_VERSION" ]; then
            echo "❌ ERROR: Version mismatch in ${{ matrix.package.name }}!"
            echo "   Release tag version: $RELEASE_VERSION"
            echo "   Package.json version: $PACKAGE_VERSION"
            echo ""
            echo "Please update the version in ${{ matrix.package.path }}/package.json to match the release tag."
            echo "Expected: \"version\": \"$RELEASE_VERSION\""
            exit 1
          fi
          
          echo "✅ ${{ matrix.package.name }} version matches release tag: $RELEASE_VERSION"

  publish:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - name: "prompt-shared-state"
            path: "prompt-shared-state"
            npm_name: "@tumaet/prompt-shared-state"
          - name: "prompt-ui-components"
            path: "prompt-ui-components"
            npm_name: "@tumaet/prompt-ui-components"

    defaults:
      run:
        working-directory: ${{ matrix.package.path }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies for ${{ matrix.package.name }}
        run: yarn install

      - name: Build ${{ matrix.package.name }}
        run: yarn build

      - name: Publish ${{ matrix.package.npm_name }} to npm
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "Publishing ${{ matrix.package.npm_name }} to npm..."
          yarn npm publish
